-- Curated starter tags. Members can add their own on top; admins merge and retire
-- from /admin/skills. Safe to re-run.
insert into public.skills (name, category) values
  ('C',                  'Languages'),
  ('C++',                'Languages'),
  ('Java',               'Languages'),
  ('Python',             'Languages'),
  ('JavaScript',         'Languages'),
  ('TypeScript',         'Languages'),
  ('Go',                 'Languages'),
  ('Rust',               'Languages'),
  ('Kotlin',             'Languages'),
  ('Swift',              'Languages'),
  ('PHP',                'Languages'),
  ('R',                  'Languages'),

  ('HTML & CSS',         'Web'),
  ('React',              'Web'),
  ('Next.js',            'Web'),
  ('Vue',                'Web'),
  ('Angular',            'Web'),
  ('Svelte',             'Web'),
  ('Tailwind CSS',       'Web'),
  ('Node.js',            'Web'),
  ('Express',            'Web'),
  ('Django',             'Web'),
  ('Flask',              'Web'),
  ('Spring Boot',        'Web'),
  ('REST APIs',          'Web'),
  ('GraphQL',            'Web'),
  ('WebSockets',         'Web'),

  ('Android',            'Mobile'),
  ('iOS',                'Mobile'),
  ('Flutter',            'Mobile'),
  ('React Native',       'Mobile'),

  ('SQL',                'Data & AI'),
  ('PostgreSQL',         'Data & AI'),
  ('MongoDB',            'Data & AI'),
  ('Firebase',           'Data & AI'),
  ('Supabase',           'Data & AI'),
  ('Redis',              'Data & AI'),
  ('Pandas',             'Data & AI'),
  ('NumPy',              'Data & AI'),
  ('Machine Learning',   'Data & AI'),
  ('Deep Learning',      'Data & AI'),
  ('PyTorch',            'Data & AI'),
  ('TensorFlow',         'Data & AI'),
  ('Computer Vision',    'Data & AI'),
  ('NLP',                'Data & AI'),
  ('Data Visualisation', 'Data & AI'),

  ('Figma',              'Design'),
  ('UI Design',          'Design'),
  ('UX Research',        'Design'),
  ('Graphic Design',     'Design'),
  ('Video Editing',      'Design'),
  ('Canva',              'Design'),

  ('Git',                'Cloud & DevOps'),
  ('Docker',             'Cloud & DevOps'),
  ('Kubernetes',         'Cloud & DevOps'),
  ('AWS',                'Cloud & DevOps'),
  ('Azure',              'Cloud & DevOps'),
  ('Google Cloud',       'Cloud & DevOps'),
  ('CI/CD',              'Cloud & DevOps'),
  ('Linux',              'Cloud & DevOps'),

  ('Cybersecurity',      'Other'),
  ('Blockchain',         'Other'),
  ('Game Development',   'Other'),
  ('Embedded Systems',   'Other'),
  ('IoT',                'Other'),
  ('Arduino',            'Other'),
  ('Technical Writing',  'Other'),
  ('Public Speaking',    'Other'),
  ('Event Management',   'Other'),
  ('Competitive Programming', 'Other')
on conflict (slug) do nothing;
